on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  show_env:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: git rev-parse origin/master

      - run: env | grep GITHUB_ | sort
